name: spfa
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  crypto: ^3.0.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  material: ^1.0.0+2
  path: ^1.8.3
  shared_preferences: ^2.2.0
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  sqflite_common_ffi: ^2.2.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
